import os
import openai
import datetime

# The start of this code was generated by asking chatGPT how to create a completion in python.

# Set up the API key
# openai.api_key = "YOUR_API_KEY"
openai.api_key = os.getenv("OPENAI_API_KEY")

# Get prompt from user
input_prompt = input("Prompt:\n")

# Use the `completion` endpoint to get a predicted continuation of a given text
response = openai.Completion.create(
    engine="text-davinci-003",
    prompt=input_prompt,
    temperature=0.5,
    max_tokens=20,
    top_p=1,
    frequency_penalty=0,
    presence_penalty=0
)

# Date time
date_time = datetime.datetime.now()
dt_str = str(date_time)

# Print the predicted continuation to console
print(response["choices"][0]["text"])

# Append the predicted continuation to file
f = open("demofile2.txt", "a")
f.write("\n----------\n")
f.write(dt_str)
f.write("\n")
f.write(input_prompt)
f.write("\n")
f.write(response["choices"][0]["text"])
f.close()